In [18]:
import pandas as pd

In [19]:
train = pd.read_csv("../data/raw/train.csv")
store = pd.read_csv("../data/raw/store.csv")

train = train.merge(store, on="Store", how="left")

C:\Users\Yamini Kasa\AppData\Local\Temp\ipykernel_19316\2820021296.py:1: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv("../data/raw/train.csv")

In [20]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [21]:
train["Date"] = pd.to_datetime(train["Date"])

train["Year"] = train["Date"].dt.year
train["Month"] = train["Date"].dt.month
train["Day"] = train["Date"].dt.day

train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,Year,Month,Day
0,1,5,2015-07-31,5263,555,1,1,0,1,c,...,1270.0,9.0,2008.0,0,NaN,NaN,NaN,2015,7,31
1,2,5,2015-07-31,6064,625,1,1,0,1,a,...,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct",2015,7,31
2,3,5,2015-07-31,8314,821,1,1,0,1,a,...,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct",2015,7,31
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,...,620.0,9.0,2009.0,0,NaN,NaN,NaN,2015,7,31
4,5,5,2015-07-31,4822,559,1,1,0,1,a,...,29910.0,4.0,2015.0,0,NaN,NaN,NaN,2015,7,31

In [30]:
train.shape

(322136, 25)

In [22]:
train.to_csv("../data/processed/train_features.csv", index=False)

In [23]:
train["PromoEffect"] = train["Promo"] * train["Promo2"]

In [24]:
train["CompetitionDistance"] = train["CompetitionDistance"].fillna(train["CompetitionDistance"].median())

In [25]:
train["IsHoliday"] = train["StateHoliday"].apply(lambda x: 1 if x != "0" else 0)

In [26]:
train = train.sort_values(["Store", "Date"])

train["Sales_Lag_1"] = train.groupby("Store")["Sales"].shift(1)

In [27]:
train["Sales_Rolling_7"] = train.groupby("Store")["Sales"].transform(lambda x: x.rolling(7).mean())

In [28]:
train = train.dropna()

In [ ]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,Promo2SinceWeek,Promo2SinceYear,PromoInterval,Year,Month,Day,PromoEffect,IsHoliday,Sales_Lag_1,Sales_Rolling_7
1009406,2,1,2013-01-07,6775,763,1,1,0,0,a,...,13.0,2010.0,"Jan,Apr,Jul,Oct",2013,1,7,1,0,0.0,3168.857143
1008291,2,2,2013-01-08,6318,685,1,1,0,0,a,...,13.0,2010.0,"Jan,Apr,Jul,Oct",2013,1,8,1,0,6775.0,4071.428571
1007176,2,3,2013-01-09,6763,785,1,1,0,0,a,...,13.0,2010.0,"Jan,Apr,Jul,Oct",2013,1,9,1,0,6318.0,4405.857143
1006061,2,4,2013-01-10,5618,637,1,1,0,0,a,...,13.0,2010.0,"Jan,Apr,Jul,Oct",2013,1,10,1,0,6763.0,4614.285714
1004946,2,5,2013-01-11,4810,539,1,1,0,0,a,...,13.0,2010.0,"Jan,Apr,Jul,Oct",2013,1,11,1,0,5618.0,4660.857143

In [31]:
train.to_csv("../data/processed/train_features.csv", index=False)

In [33]:
train.info()

<class 'pandas.DataFrame'>
Index: 322136 entries, 1009406 to 1110
Data columns (total 25 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Store                      322136 non-null  int64
 1   DayOfWeek                  322136 non-null  int64
 2   Date                       322136 non-null  datetime64[us]
 3   Sales                      322136 non-null  int64
 4   Customers                  322136 non-null  int64
 5   Open                       322136 non-null  int64
 6   Promo                      322136 non-null  int64
 7   StateHoliday               322136 non-null  object
 8   SchoolHoliday              322136 non-null  int64
 9   StoreType                  322136 non-null  str
 10  Assortment                 322136 non-null  str
 11  CompetitionDistance        322136 non-null  float64
 12  CompetitionOpenSinceMonth  322136 non-null  float64
 13  CompetitionOpenSinceYear   322136 non-null  float64
 14  Promo2                     322136 non-null  int64
 15  Promo2SinceWeek            322136 non-null  float64
 16  Promo2SinceYear            322136 non-null  float64
 17  PromoInterval              322136 non-null  str
 18  Year                       322136 non-null  int32
 19  Month                      322136 non-null  int32
 20  Day                        322136 non-null  int32
 21  PromoEffect                322136 non-null  int64
 22  IsHoliday                  322136 non-null  int64
 23  Sales_Lag_1                322136 non-null  float64
 24  Sales_Rolling_7            322136 non-null  float64
dtypes: datetime64[us](1), float64(7), int32(3), int64(10), object(1), str(3)
memory usage: 60.2+ MB

In [35]:
train.isnull().sum()

Store                        0
DayOfWeek                    0
Date                         0
Sales                        0
Customers                    0
Open                         0
Promo                        0
StateHoliday                 0
SchoolHoliday                0
StoreType                    0
Assortment                   0
CompetitionDistance          0
CompetitionOpenSinceMonth    0
CompetitionOpenSinceYear     0
Promo2                       0
Promo2SinceWeek              0
Promo2SinceYear              0
PromoInterval                0
Year                         0
Month                        0
Day                          0
PromoEffect                  0
IsHoliday                    0
Sales_Lag_1                  0
Sales_Rolling_7              0
dtype: int64

In [36]:
train.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment',
       'CompetitionDistance', 'CompetitionOpenSinceMonth',
       'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek',
       'Promo2SinceYear', 'PromoInterval', 'Year', 'Month', 'Day',
       'PromoEffect', 'IsHoliday', 'Sales_Lag_1', 'Sales_Rolling_7'],
      dtype='str')

In [37]:
train.dtypes

Store                                 int64
DayOfWeek                             int64
Date                         datetime64[us]
Sales                                 int64
Customers                             int64
Open                                  int64
Promo                                 int64
StateHoliday                         object
SchoolHoliday                         int64
StoreType                               str
Assortment                              str
CompetitionDistance                 float64
CompetitionOpenSinceMonth           float64
CompetitionOpenSinceYear            float64
Promo2                                int64
Promo2SinceWeek                     float64
Promo2SinceYear                     float64
PromoInterval                           str
Year                                  int32
Month                                 int32
Day                                   int32
PromoEffect                           int64
IsHoliday                             int64
Sales_Lag_1                         float64
Sales_Rolling_7                     float64
dtype: object

In [38]:
train.isnull().sum().sort_values(ascending=False)

Store                        0
DayOfWeek                    0
Date                         0
Sales                        0
Customers                    0
Open                         0
Promo                        0
StateHoliday                 0
SchoolHoliday                0
StoreType                    0
Assortment                   0
CompetitionDistance          0
CompetitionOpenSinceMonth    0
CompetitionOpenSinceYear     0
Promo2                       0
Promo2SinceWeek              0
Promo2SinceYear              0
PromoInterval                0
Year                         0
Month                        0
Day                          0
PromoEffect                  0
IsHoliday                    0
Sales_Lag_1                  0
Sales_Rolling_7              0
dtype: int64

In [39]:
train.to_csv("../data/processed/train_features.csv", index=False)

In [ ]:
os.path.exists("../data/processed/train_features.csv")